### ISSUE TITLE
Binary Metric: when type is Boolean, power analysis workflow throws errors.

### ISSUE THREAD

**Issue by ludovico-lanni** [david26694/cluster-experiments#12]
# Description
Right now, if the metric is binary and it is of type Boolean (True, False), the power analysis will throw a series of errors that can't be easily traced back to this reason.

# Fix Suggestions
We could either perform a conversion in the code, or raise an error specifying that the input metric should be of type integer (0,1).

**Comment by david26694** [comment]
Solved in 0.1.4
