### ISSUE TITLE
Allow relative perturbator with mixed-sign values

### ISSUE THREAD

**Issue by Gabrielcidral1** [david26694/cluster-experiments#182]
In some cases, you might want to add a relative perturbator for a target that includes negative and positive values, such as profit margin. In this case, with a positive effect of 0.5, and a target of -100,  we would the result to be -50.

@david26694 Should we create a new class for it? 

Here's a example (suggested by @matheusbuniotto)

```
class RelativeConstantPerturbator(Perturbator):
    def perturbate(
        self, df: pd.DataFrame, average_effect: Optional[float] = None
    ) -> pd.DataFrame:
        """
        Usage:

        ```python
        from cluster_experiments.perturbator import UniformPerturbator
        import pandas as pd
        df = pd.DataFrame({"target": [1, 2, 3], "treatment": ["A", "B", "A"]})
        perturbator = UniformPerturbator()
        perturbator.perturbate(df, average_effect=1)
        ```
        """
        df = df.copy().reset_index(drop=True)
        average_effect = self.get_average_effect(average_effect)
        df = self.apply_multiplicative_effect(df, average_effect)
        return df

    
    def apply_multiplicative_effect(
        self, df: pd.DataFrame, effect: Union[float, np.ndarray]
    ) -> pd.DataFrame:
        mask = df[self.treatment_col] == self.treatment
        original_values = df.loc[mask, self.target_col]
        
        # Calculate the new values
        new_values = np.where(
            original_values >= 0,
            original_values * (1 + effect),
            original_values * (1 - effect)
        )
        
        # Update the dataframe
        df.loc[mask, self.target_col] = new_values
        
        return df
```

**Comment by david26694** [comment]
Hey gabi, thanks for the issue. Couple questions?
* Any use-case or example you can think this is covering?
* I understand if effect is 0.5 and target is [-100, 10], then perturbated values are [-50, 15], right?

**Comment by Gabrielcidral1** [comment]
Our use case is to perturbate effect on profit margin, where it can be either positive or negative. And yes, your example is what we have in mind.

**Comment by david26694** [comment]
yep, feel free to create a PR!
